#pragma once
#include <cstdint>

enum output_reports : uint8_t {
    REP_OUT_RUMBLE = 0x10,
    REP_OUT_PLAYER_LED = 0x11,
    REP_OUT_DATA_REPORT_MODE = 0x12,
    REP_OUT_IR_PIXEL_CLOCK_ENABLE = 0x13,
    REP_OUT_SPEAKER_ENABLE = 0x14,
    REP_OUT_STATUS_INFORMATION_REQUEST = 0x15,
    REP_OUT_WRITE_TO_MEMORY = 0x16,
    REP_OUT_READ_FROM_MEMORY = 0x17,
    REP_OUT_SPEAKER_DATA = 0x18,
    REP_OUT_SPEAKER_MUTE = 0x19,
    REP_OUT_IR_LOGIC_ENABLE = 0x1A,
};

enum input_reports : uint8_t {
    REP_IN_STATUS_INFORMATION = 0x20,
    REP_IN_MEMORY_READ = 0x21,
    REP_IN_ACK_OUTPUT_REPORT = 0x22,
    REP_IN_BUTTONS = 0x30,
    REP_IN_BUTTONS_ACC = 0x31,
    REP_IN_BUTTONS_EXT_8B = 0x32,
    REP_IN_BUTTONS_ACC_IR_12B = 0x33,
    REP_IN_BUTTONS_EXT_19B = 0x34,
    REP_IN_BUTTONS_ACC_EXT_16B = 0x35,
    REP_IN_BUTTONS_IR_10B_EXTENSION_9B = 0x36,
    REP_IN_BUTTONS_ACC_IR_10B_EXTENSION_6B = 0x37,

    // Interleaved
    REP_IN_BUTTONS_ACC_IR_36B = 0x3E,
    REP_IN_BUTTONS_ACC_IR_36B_ALT = 0x3F
};
